[server]
port = "3838" # listening port of the server

[period]
heartbeat_period = 2 #secondes
ping_period = 5 #secondes

[debug]
debug_level = 'All'  #All,Info,Warning,Error,Quiet,
debug_datagram_handler = true
debug_ping_sender = true
debug_data_handler = true
debug_heartbeat_checker = true
debug_topic_handler = true
debug_client_manager = true

